[project]
name = "customer-support-fde"
version = "0.8.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "agentevals>=0.0.9",
    "arize-phoenix-otel>=0.17.1",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.1",
    "langgraph>=1.2.11",
    "openinference-instrumentation-langchain>=0.1.76",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
customer-support-fde = "customer_support_fde:main"

[tool.pytest.ini_options]
addopts = "--basetemp=.pytest-tmp"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
